name: dosbox-staging
adopt-info: dosbox-staging
summary: Open Source PC/MS-DOS emulator
description: |
  DOSBox is a DOS-emulator that uses the SDL-library which 
  makes DOSBox very easy to port to different platforms. DOSBox has 
  already been ported to many different platforms, such as Windows, BeOS, 
  Linux, MacOS X...
  
  DOSBox also emulates CPU:286/386 realmode/protected mode, 
  Directory FileSystem/XMS/EMS, Tandy/Hercules/CGA/EGA/VGA/VESA graphics, 
  a SoundBlaster/Gravis Ultra Sound card for excellent sound compatibility 
  with older games...
  
  You can "re-live" the good old days with the help of DOSBox, it 
  can run plenty of the old classics that don't run on your new computer!  
  
  DOSBox is totally free of charge and OpenSource.

grade: stable
confinement: strict
base: core18

apps:
  dosbox-staging:
    command: desktop-launch dosbox
    plugs: [audio-playback, home, pulseaudio, desktop, desktop-legacy, wayland, x11, opengl, removable-media]
    extensions: [gnome-3-28]

parts:
  dosbox-staging:
    plugin: autotools
    source: https://github.com/dosbox-staging/dosbox-staging.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags `git rev-list --tags --max-count=1`)"
      echo $last_committed_tag
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      echo $last_released_tag
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        echo "Setting version to $last_committed_tag"
        snapcraftctl set-version "${last_committed_tag}"
      else
        echo "Setting version to $(git rev-parse --short HEAD)"
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    build-packages:
      - libsdl2-dev
      #- libsdl-sound1.2-dev
      #- libasound2-dev
      - libopus-dev
      - libopusfile-dev
    stage-packages:
      - libsdl2-2.0-0
      #- libsdl-net1.2
      #- libsdl-sound1.2
      #- libasound2
      - libslang2
      - libglu1-mesa
      - libopusfile0
      - freeglut3
    organize:
      usr/lib/*/libpulse.so.*: usr/lib/
      usr/lib/*/pulseaudio/libpulsecommon*: usr/lib/
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  cleanup:
    after: [dosbox-staging]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
